from app.schemas.base import (
    BaseSchema,
    BaseResponseSchema,
    PaginatedResponse,
    MessageResponse,
)
from app.schemas.permission import (
    PermissionSourceCreateSchema,
    PermissionSourceUpdateSchema,
    PermissionSourceResponseSchema,
    PermissionCreateSchema,
    PermissionUpdateSchema,
    PermissionResponseSchema,
    PermissionListSchema,
    EnregistrementPermissionsSchema,
)
from app.schemas.role import (
    RoleCreateSchema,
    RoleUpdateSchema,
    AjouterPermissionsSchema,
    RetirerPermissionsSchema,
    RoleResponseSchema,
    RoleListSchema,
)
from app.schemas.groupe import (
    GroupeCreateSchema,
    GroupeUpdateSchema,
    AjouterRolesGroupeSchema,
    GroupeRoleSchema,
    GroupeResponseSchema,
    GroupeListSchema,
)
from app.schemas.profil_local import (
    ProfilLocalCreateSchema,
    ProfilLocalUpdateSchema,
    ProfilSyncSchema,
    SuspendreProfilSchema,
    ProfilResponseSchema,
    ProfilListSchema,
)
from app.schemas.assignation import (
    AssignationRoleCreateSchema,
    AssignationRoleUpdateSchema,
    RevoquerAssignationSchema,
    AssignationRoleResponseSchema,
    AssignationGroupeCreateSchema,
    AssignationGroupeResponseSchema,
)
from app.schemas.delegation import (
    DelegationCreateSchema,
    RevoquerDelegationSchema,
    DelegationResponseSchema,
)
from app.schemas.habilitation import (
    PermissionEffective,
    HabilitationsSchema,
    VerifierPermissionSchema,
    ResultatVerificationSchema,
    TokenSessionSchema,
)
from app.schemas.journal import (
    JournalAccesResponseSchema,
    FiltresJournalSchema,
)
from app.schemas.token_schemas import (
    # Tokens
    AccessTokenPayload,
    AccessTokenResponse,
    RefreshTokenPayload,
    RefreshTokenResponse,
    # Sessions
    SessionInfo,
    SessionCreateRequest,
    # Authentification
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    # Validation
    TokenValidationRequest,
    TokenValidationResponse,
    EndpointAuthorizationCheck,
    # Blacklist
    BlacklistEntry,
    BlacklistInfo,
    # Synchronisation
    IAMCentralUserData,
    IAMCentralStatusCheck,
    SyncBatchRequest,
    SyncBatchResponse,
    # Métriques
    TokenMetrics,
    SessionStats,
    # Erreurs
    TokenErrorDetail,
    TokenValidationError,
)

__all__ = [
    "BaseSchema",
    "BaseResponseSchema",
    "PaginatedResponse",
    "MessageResponse",
    "PermissionSourceCreateSchema",
    "PermissionSourceUpdateSchema",
    "PermissionSourceResponseSchema",
    "PermissionCreateSchema",
    "PermissionUpdateSchema",
    "PermissionResponseSchema",
    "PermissionListSchema",
    "EnregistrementPermissionsSchema",
    "RoleCreateSchema",
    "RoleUpdateSchema",
    "AjouterPermissionsSchema",
    "RetirerPermissionsSchema",
    "RoleResponseSchema",
    "RoleListSchema",
    "GroupeCreateSchema",
    "GroupeUpdateSchema",
    "AjouterRolesGroupeSchema",
    "GroupeRoleSchema",
    "GroupeResponseSchema",
    "GroupeListSchema",
    "ProfilLocalCreateSchema",
    "ProfilLocalUpdateSchema",
    "ProfilSyncSchema",
    "SuspendreProfilSchema",
    "ProfilResponseSchema",
    "ProfilListSchema",
    "AssignationRoleCreateSchema",
    "AssignationRoleUpdateSchema",
    "RevoquerAssignationSchema",
    "AssignationRoleResponseSchema",
    "AssignationGroupeCreateSchema",
    "AssignationGroupeResponseSchema",
    "DelegationCreateSchema",
    "RevoquerDelegationSchema",
    "DelegationResponseSchema",
    "PermissionEffective",
    "HabilitationsSchema",
    "VerifierPermissionSchema",
    "ResultatVerificationSchema",
    "TokenSessionSchema",
    "JournalAccesResponseSchema",
    "FiltresJournalSchema",
    # Token schemas
    "AccessTokenPayload",
    "AccessTokenResponse",
    "RefreshTokenPayload",
    "RefreshTokenResponse",
    "SessionInfo",
    "SessionCreateRequest",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "TokenValidationRequest",
    "TokenValidationResponse",
    "EndpointAuthorizationCheck",
    "BlacklistEntry",
    "BlacklistInfo",
    "IAMCentralUserData",
    "IAMCentralStatusCheck",
    "SyncBatchRequest",
    "SyncBatchResponse",
    "TokenMetrics",
    "SessionStats",
    "TokenErrorDetail",
    "TokenValidationError",
]
