"""auto_migration_20260420_092731

Revision ID: 89ec81ffa4c8
Revises: 0001_initial_schema
Create Date: 2026-04-20 09:27:32.996741

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '89ec81ffa4c8'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignations_groupe', sa.Column('ajoute_par', sa.UUID(), nullable=True))
    op.add_column('assignations_groupe', sa.Column('retire_par', sa.UUID(), nullable=True))
    op.add_column('assignations_groupe', sa.Column('date_retrait', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assignations_groupe', sa.Column('raison', sa.Text(), nullable=True))
    op.drop_index('ix_assignations_groupe_statut', table_name='assignations_groupe')
    op.drop_column('assignations_groupe', 'perimetre')
    op.drop_column('assignations_groupe', 'assigne_par')
    op.alter_column('assignations_role', 'perimetre',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Périmètre d'application du rôle. ex: {campus_id, composante_id, departement_id, filiere_id, annee_academique}",
               existing_nullable=True)
    op.alter_column('assignations_role', 'date_fin',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="null = pas d'expiration",
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'user_id_national',
               existing_type=sa.UUID(),
               comment="UUID de l'utilisateur dans IAM Central. NULL uniquement pour le compte bootstrap temporaire.",
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'username',
               existing_type=sa.VARCHAR(length=150),
               comment='Identifiant de connexion locale généré automatiquement',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'nb_connexions',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hash sécurisé du mot de passe local (bcrypt)',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'password_salt',
               existing_type=sa.VARCHAR(length=255),
               comment='Sel cryptographique pour le hash',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'password_algorithm',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='Algorithme de hash : bcrypt, argon2, pbkdf2...',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'password_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date du dernier changement de mot de passe',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Nombre de tentatives de connexion échouées',
               existing_nullable=False)
    op.alter_column('comptes_locaux', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date jusqu'à laquelle le compte est verrouillé",
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'require_password_change',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Le compte doit changer son mot de passe à la prochaine connexion',
               existing_nullable=False)
    op.alter_column('comptes_locaux', 'snapshot_iam_central',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Snapshot complet des données IAM Central au moment de la dernière synchronisation SSO. NULL pour le compte bootstrap.',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Préférences UI, langue, notifications...',
               existing_nullable=True)
    op.alter_column('delegations', 'role_id',
               existing_type=sa.UUID(),
               comment='null = délégation de permissions spécifiques',
               existing_nullable=True)
    op.alter_column('delegations', 'permissions_specifiques',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Liste de codes de permissions si pas de rôle',
               existing_nullable=True)
    op.alter_column('endpoint_permissions', 'public',
               existing_type=sa.BOOLEAN(),
               comment='Si true, endpoint accessible sans authentification',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('ix_endpoint_source', 'endpoint_permissions', ['source_id'], unique=False)
    op.create_index('ix_endpoint_source_path_method', 'endpoint_permissions', ['source_id', 'path', 'method'], unique=True)
    op.alter_column('groupes', 'perimetre',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Périmètre commun à tous les membres du groupe. ex: {composante_id: uuid, annee_academique: 2024-2025}',
               existing_nullable=True)
    op.alter_column('groupes', 'actif',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('permission_sources', 'actif',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('permission_sources', 'nb_permissions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('permissions', 'actif',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('permissions', 'necessite_perimetre',
               existing_type=sa.BOOLEAN(),
               comment='Si true, doit être assignée avec un périmètre',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('permissions', 'deprecated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('permissions', 'exemple_perimetre',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Exemple de périmètre valide pour cette permission',
               existing_nullable=True)
    op.alter_column('profils_locaux', 'compte_id',
               existing_type=sa.UUID(),
               comment="CompteLocal auquel appartient ce profil. C'est le compte qui porte l'identité et le lien IAM Central.",
               existing_nullable=False)
    op.alter_column('profils_locaux', 'username',
               existing_type=sa.VARCHAR(length=150),
               comment='Identifiant de connexion locale — dénormalisé depuis CompteLocal',
               existing_nullable=True)
    op.alter_column('profils_locaux', 'type_profil',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profils_locaux', 'nb_connexions',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profils_locaux', 'contexte_scolaire',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Contexte métier propre à ce profil : {filiere, composante, departement, annee_academique, niveau, specialite, numero_etudiant_local, ...}',
               existing_nullable=True)
    op.alter_column('profils_locaux', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Préférences UI spécifiques à ce profil',
               existing_nullable=True)
    op.alter_column('roles', 'perimetre_obligatoire',
               existing_type=sa.BOOLEAN(),
               comment='Si true, ce rôle doit être assigné avec un périmètre explicite',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'perimetre_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Schéma des champs de périmètre attendus',
               existing_nullable=True)
    op.alter_column('roles', 'actif',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'systeme',
               existing_type=sa.BOOLEAN(),
               comment='Si true, rôle non modifiable par les admins',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('token_manager', 'access_token_hash',
               existing_type=sa.VARCHAR(length=128),
               comment="Hash du token d'accès",
               existing_nullable=False)
    op.alter_column('token_manager', 'refresh_token_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='Hash du token de rafraîchissement',
               existing_nullable=False)
    op.alter_column('token_manager', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('token_manager', 'last_used',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('token_manager', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('token_manager', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('token_manager', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('token_manager', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               nullable=False,
               comment='ID unique du device')
    op.alter_column('token_manager', 'device_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('token_manager', 'activity_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_token_manager_device', 'token_manager', ['device_id'], unique=False)
    op.create_index('idx_token_manager_expires', 'token_manager', ['expires_at'], unique=False)
    op.create_index('idx_token_manager_revoked', 'token_manager', ['is_revoked'], unique=False)
    op.create_index('idx_token_manager_session', 'token_manager', ['session_id'], unique=False)
    op.create_index('idx_token_manager_user_active', 'token_manager', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_token_manager_device_id'), 'token_manager', ['device_id'], unique=False)
    op.create_index(op.f('ix_token_manager_is_active'), 'token_manager', ['is_active'], unique=False)
    op.create_index(op.f('ix_token_manager_is_revoked'), 'token_manager', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_token_manager_session_id'), 'token_manager', ['session_id'], unique=True)
    op.create_table_comment(
        'token_manager',
        'Gestionnaire des tokens JWT avec tracking détaillé des devices',
        existing_comment=None,
        schema=None
    )
    op.alter_column('token_settings', 'access_token_lifetime',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment="Durée de vie du token d'accès en minutes",
               existing_nullable=False)
    op.alter_column('token_settings', 'refresh_token_lifetime',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Durée de vie du token de rafraîchissement en minutes (7 jours)',
               existing_nullable=False)
    op.alter_column('token_settings', 'max_sessions_per_user',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Nombre maximum de sessions actives par utilisateur',
               existing_nullable=False)
    op.alter_column('token_settings', 'session_ttl_hours',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Durée de vie des sessions en heures',
               existing_nullable=False)
    op.alter_column('token_settings', 'rotate_refresh_tokens',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Générer un nouveau token de rafraîchissement à chaque utilisation',
               existing_nullable=False)
    op.alter_column('token_settings', 'enable_blacklist',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Activer la liste noire des tokens',
               existing_nullable=False)
    op.alter_column('token_settings', 'blacklist_ttl_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Durée de conservation en liste noire (24h)',
               existing_nullable=False)
    op.alter_column('token_settings', 'require_https',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Exiger HTTPS pour les tokens',
               existing_nullable=False)
    op.alter_column('token_settings', 'validate_ip',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment="Valider l'IP de l'utilisateur",
               existing_nullable=False)
    op.alter_column('token_settings', 'validate_user_agent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Valider le User-Agent',
               existing_nullable=False)
    op.alter_column('token_settings', 'encrypt_tokens',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Chiffrer les tokens en base',
               existing_nullable=False)
    op.alter_column('token_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Configuration active',
               existing_nullable=False)
    op.alter_column('token_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('token_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_token_settings_active', 'token_settings', ['is_active'], unique=False)
    op.create_index('idx_token_settings_name', 'token_settings', ['name'], unique=False)
    op.create_table_comment(
        'token_settings',
        'Configurations des paramètres de sécurité des tokens JWT',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'token_settings',
        existing_comment='Configurations des paramètres de sécurité des tokens JWT',
        schema=None
    )
    op.drop_index('idx_token_settings_name', table_name='token_settings')
    op.drop_index('idx_token_settings_active', table_name='token_settings')
    op.alter_column('token_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('token_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('token_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Configuration active',
               existing_nullable=False)
    op.alter_column('token_settings', 'encrypt_tokens',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Chiffrer les tokens en base',
               existing_nullable=False)
    op.alter_column('token_settings', 'validate_user_agent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Valider le User-Agent',
               existing_nullable=False)
    op.alter_column('token_settings', 'validate_ip',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment="Valider l'IP de l'utilisateur",
               existing_nullable=False)
    op.alter_column('token_settings', 'require_https',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Exiger HTTPS pour les tokens',
               existing_nullable=False)
    op.alter_column('token_settings', 'blacklist_ttl_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1440'),
               comment=None,
               existing_comment='Durée de conservation en liste noire (24h)',
               existing_nullable=False)
    op.alter_column('token_settings', 'enable_blacklist',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Activer la liste noire des tokens',
               existing_nullable=False)
    op.alter_column('token_settings', 'rotate_refresh_tokens',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Générer un nouveau token de rafraîchissement à chaque utilisation',
               existing_nullable=False)
    op.alter_column('token_settings', 'session_ttl_hours',
               existing_type=sa.INTEGER(),
               server_default=sa.text('24'),
               comment=None,
               existing_comment='Durée de vie des sessions en heures',
               existing_nullable=False)
    op.alter_column('token_settings', 'max_sessions_per_user',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               comment=None,
               existing_comment='Nombre maximum de sessions actives par utilisateur',
               existing_nullable=False)
    op.alter_column('token_settings', 'refresh_token_lifetime',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10080'),
               comment=None,
               existing_comment='Durée de vie du token de rafraîchissement en minutes (7 jours)',
               existing_nullable=False)
    op.alter_column('token_settings', 'access_token_lifetime',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               comment=None,
               existing_comment="Durée de vie du token d'accès en minutes",
               existing_nullable=False)
    op.drop_table_comment(
        'token_manager',
        existing_comment='Gestionnaire des tokens JWT avec tracking détaillé des devices',
        schema=None
    )
    op.drop_index(op.f('ix_token_manager_session_id'), table_name='token_manager')
    op.drop_index(op.f('ix_token_manager_is_revoked'), table_name='token_manager')
    op.drop_index(op.f('ix_token_manager_is_active'), table_name='token_manager')
    op.drop_index(op.f('ix_token_manager_device_id'), table_name='token_manager')
    op.drop_index('idx_token_manager_user_active', table_name='token_manager')
    op.drop_index('idx_token_manager_session', table_name='token_manager')
    op.drop_index('idx_token_manager_revoked', table_name='token_manager')
    op.drop_index('idx_token_manager_expires', table_name='token_manager')
    op.drop_index('idx_token_manager_device', table_name='token_manager')
    op.alter_column('token_manager', 'activity_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('token_manager', 'device_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('token_manager', 'device_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='ID unique du device')
    op.alter_column('token_manager', 'session_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('token_manager', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('token_manager', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('token_manager', 'last_used',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('token_manager', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('token_manager', 'refresh_token_hash',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Hash du token de rafraîchissement',
               existing_nullable=False)
    op.alter_column('token_manager', 'access_token_hash',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment="Hash du token d'accès",
               existing_nullable=False)
    op.alter_column('roles', 'systeme',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si true, rôle non modifiable par les admins',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'actif',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('roles', 'perimetre_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Schéma des champs de périmètre attendus',
               existing_nullable=True)
    op.alter_column('roles', 'perimetre_obligatoire',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si true, ce rôle doit être assigné avec un périmètre explicite',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('profils_locaux', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Préférences UI spécifiques à ce profil',
               existing_nullable=True)
    op.alter_column('profils_locaux', 'contexte_scolaire',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Contexte métier propre à ce profil : {filiere, composante, departement, annee_academique, niveau, specialite, numero_etudiant_local, ...}',
               existing_nullable=True)
    op.alter_column('profils_locaux', 'nb_connexions',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'0'::character varying"),
               existing_nullable=True)
    op.alter_column('profils_locaux', 'type_profil',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'invite'::character varying"),
               existing_nullable=False)
    op.alter_column('profils_locaux', 'username',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Identifiant de connexion locale — dénormalisé depuis CompteLocal',
               existing_nullable=True)
    op.alter_column('profils_locaux', 'compte_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="CompteLocal auquel appartient ce profil. C'est le compte qui porte l'identité et le lien IAM Central.",
               existing_nullable=False)
    op.alter_column('permissions', 'exemple_perimetre',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Exemple de périmètre valide pour cette permission',
               existing_nullable=True)
    op.alter_column('permissions', 'deprecated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('permissions', 'necessite_perimetre',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si true, doit être assignée avec un périmètre',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('permissions', 'actif',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('permission_sources', 'nb_permissions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('permission_sources', 'actif',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('groupes', 'actif',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('groupes', 'perimetre',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Périmètre commun à tous les membres du groupe. ex: {composante_id: uuid, annee_academique: 2024-2025}',
               existing_nullable=True)
    op.drop_index('ix_endpoint_source_path_method', table_name='endpoint_permissions')
    op.drop_index('ix_endpoint_source', table_name='endpoint_permissions')
    op.alter_column('endpoint_permissions', 'public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si true, endpoint accessible sans authentification',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('delegations', 'permissions_specifiques',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Liste de codes de permissions si pas de rôle',
               existing_nullable=True)
    op.alter_column('delegations', 'role_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='null = délégation de permissions spécifiques',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Préférences UI, langue, notifications...',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'snapshot_iam_central',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Snapshot complet des données IAM Central au moment de la dernière synchronisation SSO. NULL pour le compte bootstrap.',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'require_password_change',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Le compte doit changer son mot de passe à la prochaine connexion',
               existing_nullable=False)
    op.alter_column('comptes_locaux', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date jusqu'à laquelle le compte est verrouillé",
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Nombre de tentatives de connexion échouées',
               existing_nullable=False)
    op.alter_column('comptes_locaux', 'password_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date du dernier changement de mot de passe',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'password_algorithm',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'bcrypt'::character varying"),
               comment=None,
               existing_comment='Algorithme de hash : bcrypt, argon2, pbkdf2...',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'password_salt',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Sel cryptographique pour le hash',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hash sécurisé du mot de passe local (bcrypt)',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'nb_connexions',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'0'::character varying"),
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'username',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Identifiant de connexion locale généré automatiquement',
               existing_nullable=True)
    op.alter_column('comptes_locaux', 'user_id_national',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="UUID de l'utilisateur dans IAM Central. NULL uniquement pour le compte bootstrap temporaire.",
               existing_nullable=True)
    op.alter_column('assignations_role', 'date_fin',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="null = pas d'expiration",
               existing_nullable=True)
    op.alter_column('assignations_role', 'perimetre',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="Périmètre d'application du rôle. ex: {campus_id, composante_id, departement_id, filiere_id, annee_academique}",
               existing_nullable=True)
    op.add_column('assignations_groupe', sa.Column('assigne_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('assignations_groupe', sa.Column('perimetre', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_assignations_groupe_statut', 'assignations_groupe', ['statut'], unique=False)
    op.drop_column('assignations_groupe', 'raison')
    op.drop_column('assignations_groupe', 'date_retrait')
    op.drop_column('assignations_groupe', 'retire_par')
    op.drop_column('assignations_groupe', 'ajoute_par')
    # ### end Alembic commands ###
